config/routes.rb
Rails.application.routes.draw do

  get '/pokemon', to: 'pokemons#index'

  get '/starwar', to: 'starwars#index'

  patch '/starwars/:id', to: "starwars#update", as: 'update_starwar'
  
  patch '/pokemons/:id', to: "pokemons#update", as: 'update_pokemon'

  get '/fights', to: 'fights#index'

 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    include HTTParty
    base_uri 'http://pokeapi.co/api/v2/'

    def self.generate(api_id)
        pokemon = find_by api_id: api_id
        return pokemon unless pokemon.nil?

        response = get "/pokemon/#{api_id}"

        poke_image = get "/pokemon/#{api_id}"
        
        create!(name: response["name"],
                image: poke_image["sprites"]["front_default"],
                wins: 0,
                api_id: api_id)
    end
end

app/models/star_war.rb
class StarWar < ApplicationRecord
    include HTTParty
    base_uri 'http://swapi.co/api/people'

    def self.generate(api_id)
        star_war = find_by api: api_id
        return star_war unless star_war.nil?

        response = get "/#{api_id}"
        placeholder_image = "https://www.placecage.com/c/#{200 + api_id}/#{200 + api_id}"

        create!(name: response['name'],
                image: placeholder_image,
                wins: 0,
                api: api_id)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def index
    @star_war = StarWar.generate(rand(90))

    @pokemon = Pokemon.generate(rand(162))
  end
  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.order(wins: :desc)
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    @pokemon.update!(wins: @pokemon.wins + 1)
    redirect_to fights_url
  end
end

app/controllers/starwars_controller.rb
class StarwarsController < ApplicationController

  def index
    @star_wars = StarWar.order(wins: :desc)
  end

  def update
    @star_war = StarWar.find(params[:id])
    @star_war.update!(wins: @star_war.wins + 1)
    redirect_to fights_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/star_wars_helper.rb
module StarWarsHelper
end

app/views/fights/index.html.erb
<h1> WHO WOULD WIN? </h1>

<div> 
    <%= image_tag @star_war.image %>
    <h1><%= @star_war.name %> </h1>
    <%= button_to @star_war.name, update_starwar_path(@star_war), :method => :patch %>
</div>

<div>
    <h1> <%= @pokemon.name %> </h1>
    <%= image_tag @pokemon.image %>  
    <%= button_to @pokemon.name, update_pokemon_path(@pokemon), :method => :patch %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonVsStarwars1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<% @pokemons.each do |pokemon| %>
    <h2> <%= pokemon.name %> </h2>
    <h3> <%= pokemon.wins %></h3>
<% end %>

app/views/pokemons/update.html.erb
<h1>Pokemons#update</h1>
<p>Find me in app/views/pokemons/update.html.erb</p>

app/views/starwars/index.html.erb
<% @star_wars.each do |starwar| %>
    <h2> <%= starwar.name %> </h2>
    <h3> <%= starwar.wins %></h3>
<% end %>

app/views/starwars/update.html.erb
<h1>StarWars#update</h1>
<p>Find me in app/views/star_wars/update.html.erb</p>